test:
  sidekiq_redis:
    url: 'redis://127.0.0.1:6379/3'
    namespace: Base5

development:
  sidekiq_redis:
    url: 'redis://127.0.0.1:6379/2'
    namespace: Base5

staging:
  sidekiq_redis:
    url: 'redis://127.0.0.1:6379/1'
    namespace: Base5

production:
  sidekiq_redis:
    url: 'redis://127.0.0.1:6379/0'
    namespace: Base5
